<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_nav2_bot">
    
    <!--机器人身体-->
    <xacro:property name="chassis_length" value="0.4"/>
    <xacro:property name="chassis_width" value="0.3"/>
    <xacro:property name="chassis_height" value="0.1"/>

    <!--轮子形态-->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.04"/>

    <!--轮子位置-->
    <xacro:property name="wheel_offset_x" value="${chassis_length / 2 - 0.05}"/>
    <xacro:property name="wheel_offset_y" value="${chassis_width / 2 + wheel_width / 2}"/>
    <xacro:property name="wheel_offset_z" value="-0.02"/>
    
    <!--雷达形态-->
    <xacro:property name="laser_radius" value="0.03"/>
    <xacro:property name="laser_height" value="0.04"/>

    <!--机器人机身的物理属性-->
    <xacro:macro name="inertial_box" params="mass l w h *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (w*w + h*h)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (l*l + h*h)}" iyz="0.0"
                    izz="${(1/12) * mass * (l*l + w*w)}"/>
        </inertial>
    </xacro:macro>

    <!--机器人轮胎的物理属性-->
    <xacro:macro name="inertial_cylinder" params="mass r h *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (3*r*r + h*h)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*r*r + h*h)}" iyz="0.0"
                    izz="${(1/2) * mass * r*r}"/>
        </inertial>
    </xacro:macro>

    <!--声明材质颜色-->
    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!--机器人本体中心-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0"/>
            <!--身体大小-->
            <geometry>
                <!--长方体-->
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <!--碰撞箱-->
        <collision>
            <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0"/>
            <!--身体大小-->
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <!--物理属性-->
        <xacro:inertial_box mass="5.0" l="${chassis_length}" w="${chassis_width}" h="${chassis_height}">
            <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!--机器人中心在底面的投影-->
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${chassis_height/2 - wheel_offset_z}" rpy="0 0 0"/>
    </joint>

    <!--轮子-->
    <xacro:macro name="wheel" params="prefix reflect_x reflect_y">
        
        <link name="${prefix}_wheel_link">
            <visual>
                <!--roll需要为pi/2的原因是圆柱体默认朝z轴向上-->
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <!--圆柱体-->
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="0.5" r="${wheel_radius}" h="${wheel_width}">
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${reflect_x * wheel_offset_x} ${reflect_y * wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
            <!--旋转轴-->
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="front_left" reflect_x="1" reflect_y="1"/>
    <xacro:wheel prefix="front_right" reflect_x="1" reflect_y="-1"/>
    <xacro:wheel prefix="rear_left" reflect_x="-1" reflect_y="1"/>
    <xacro:wheel prefix="rear_right" reflect_x="-1" reflect_y="-1"/>

    <!--雷达-->
    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <!--
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
        </collision>
        -->
        <xacro:inertial_cylinder mass="0.1" r="${laser_radius}" h="${laser_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_link"/>
        <origin xyz="0 0 ${chassis_height + laser_height / 2}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="laser_link">
        <sensor name="gpu_lidar" type="gpu_lidar">
            <topic>scan</topic>
            <pose>0 0 0 0 0 0</pose>
            <frame_id>laser_link</frame_id>
            <gz_frame_id>laser_link</gz_frame_id>
            <visualize>true</visualize> <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.12</min>
                    <max>12.0</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
            <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
                <render_engine>ogre2</render_engine>
            </plugin>
        </sensor>
        <sensor name="camera" type="camera">
            <pose>0.2 0 0.2 0 0 0</pose> <update_rate>30</update_rate>
            <frame_id>laser_link</frame_id>
            <gz_frame_id>laser_link</gz_frame_id>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic> 
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin
            filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
            <left_joint>front_left_wheel_joint</left_joint> 
            <right_joint>front_right_wheel_joint</right_joint>

            <wheel_separation>${chassis_width + wheel_width}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
            <frame_id>odom</frame_id>
            <child_frame_id>base_footprint</child_frame_id>
            <publish_odom_tf>true</publish_odom_tf>
            <use_gz_time>true</use_gz_time>
        </plugin>

        <plugin
            filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
        </plugin>
    </gazebo>
</robot>